version: "3.3"

services:
  code-server:
    container_name: code-server
    build: ./docker/code
    ports:
      - "8080:8080"
      - 3000:3000
    volumes:
      - "./:/home/coder/project"
      - "./code-server:/home/coder/.local/share/code-server"
    environment:
      PASSWORD: "12345"

  react:
    container_name: react-container
    image: "react"
    build: ./
    command: "yarn start"
    environment: 
      - CI=true 
    ports:
      - 3000:3000
    volumes:
      - "./src:/home/projects/src"
      - "./public:/home/projects/public"
      - "./tsconfig.json:/home/projects/tsconfig.json"
  
  test:
    container_name: react-test
    image: react
    build: ./
    command: "yarn test"
    environment: 
      - CI="true"
    volumes:
      - "./src:/home/projects/src"
      - "./public:/home/projects/public"
      - "./tsconfig.json:/home/projects/tsconfig.json"    
  build:
    container_name: react-container
    container_name: react-test
    image: react
    build: ./
    command: "yarn build"
    volumes:
      - "./src:/home/projects/src"
      - "./public:/home/projects/public"
      - "./tsconfig.json:/home/projects/tsconfig.json"
