name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker-compose build
      - name: Test
        run: docker-compose run test
      - name: Build
        run: docker-compose run build

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker-compose build
      - name: Test
        run: docker-compose run test
      - name: Build
        run: docker-compose run build
