name: Testing

on:
  push:
    paths:
      - "*"
      - "!*.md"
      - "!*.yml"
    branches:
      - master
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Using ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, and test
        run: |
          yarn
          yarn  test
        env:
          CI: false